version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
#    image: xmog-contest-bot
    container_name: transmog-backend

    volumes:
     - ./migrations:/usr/src/app/migrations
     - ./src:/usr/src/app/src
     - ./test:/usr/src/app/test
     - ./.env:/usr/src/app/.env
     - ./console.ts:/usr/src/app/console.ts
     - ./database.json:/usr/src/app/database.json
     - ./mocha.opts:/usr/src/app/mocha.opts
     - ./package.json:/usr/src/app/package.json
     - ./package-lock.json:/usr/src/app/package-lock.json
#     - ./prod-db.db3:/usr/src/app/prod-db.db3
     - ./run.ts:/usr/src/app/run.ts
     - ./site.ts:/usr/src/app/site.ts
     - ./tsconfig.json:/usr/src/app/tsconfig.json
     - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
     - ./db:/usr/src/app/db
     - discord-bot-node-modules:/usr/src/app/node_modules
     - discord-bot-build:/usr/src/app/build

    ports:
      - "9000:9000"

#    build: .
#    develop:
#      watch:
#        - action: sync
#          path: ./db/
#          target: /usr/src/app/db/


volumes:
  discord-bot-node-modules:
  discord-bot-build:
